### ISSUE TITLE
Add a pattern to get a `Param` from an `:!`

### ISSUE THREAD

**Issue by JustusAdam** [int-index/named#13]
I find myself having a function which takes keyword arguments only to pass them onto another function that also takes the same named parameters like so

```hs
foo :: "x" :! Int -> ...
foo (Arg x) = bar ! #x x
```

Would it be possible to add a view pattern (or pattern synonym) that transforms an `:!` to a `Param`, lets call it `retain` for now. 

```hs
foo :: "x" :! Int -> ...
foo (retain -> x) = bar ! x

**Comment by int-index** [comment]
Hm-m-m. When I added `Param` I did not realise that it would make pass-through more complicated. With `named-0.1` you could just do this:

```
foo :: x `Named` "foo" -> ...
foo x = bar ! x
```

Now in `named-0.2` there's this `Param` wrapper so it no longer works... I need to think of a good solution, but for now I can suggest using an internal constructor as a temporary workaround:

```
import Named.Internal (Param(Param))

foo :: "x" :! Int -> ...
foo (Param -> x) = bar ! x
```

**Comment by JustusAdam** [comment]
Okay, thanks. 😃

**Comment by int-index** [comment]
No problem! Reopen if the suggested solution doesn't work

**Comment by JustusAdam** [comment]
It does. I chose to use a smart constructor though, to make it more future proof.

```hs
named :: name :! a -> Param (name :! a)
named = Param

foo :: "x" :! Int -> ...
foo (named -> x) = bar ! x
```
