### ISSUE TITLE
Add 'Num', 'IsString' instances to 'Name'

### ISSUE THREAD

**Issue by ChShersh** [int-index/named#2]
So it should be possible to write something like this:

```haskell
foo ! #block_count 3
    ! #block_label "smth"
```

**Comment by int-index** [comment]
It's already possible to write that.

**Comment by int-index** [comment]
In the example above, you will have the following types:

```
#block_count :: Num n => n -> Named n "block_count"
#block_label :: IsString s => s -> Named s "block_label"
```

As you can see, there is no need to have `Num` or `IsString` instances for `Named` itself.
