### ISSUE TITLE
Think of design to specify default arguments values

### ISSUE THREAD

**Issue by ChShersh** [int-index/named#3]
Just wonder: can it be possible to specify default values of arguments so you don't need to pass them explicitly? With such feature implemented Haskell can have full named arguments support which is rather cool!

**Comment by int-index** [comment]
Yes, I was wondering that as well. With the current design I do not know how to achieve that, but I'll keep this issue open in case something interesting comes up.

**Comment by int-index** [comment]
first prototype in #9 is merged now
